import assert from 'node:assert/strict';
import fs from 'node:fs';
const renderer = fs.readFileSync(new URL('../src/render/threeRenderer.js', import.meta.url), 'utf8');
const factory = fs.readFileSync(new URL('../src/render/celestialFactory.js', import.meta.url), 'utf8');
assert.match(renderer, /new THREE\.PointLight\(0xffffff,\s*5\.5,\s*0,\s*0\)/, 'stellar renderer light must remain exposure-normalized with no render-space attenuation');
assert.match(renderer, /sunLight\.color\.setHex\(body\.color/, 'stellar light should inherit generated star color');
assert.match(renderer, /new THREE\.AmbientLight\(0x263149,\s*0\.055\)/, 'ambient light should remain intentionally low');
assert.match(factory, /strictPhysicalDisk/, 'planets, moons and rogues should use physical radii instead of minimum visual disk inflation');
assert.match(factory, /physicalReflector \? 0x000000 : bodyColor/, 'physical planets and moons must not self-emit their body color');
assert.match(factory, /physicalReflector \? 0 : 0\.13/, 'only legacy non-planetary proxy bodies retain the old exposure-floor emissive term');
assert.match(factory, /small-body-readability-proxy/, 'readability shell should remain isolated to non-planetary proxy bodies');
assert.match(factory, /stellarVisibilityAtBody/, 'planet/moon material should consume body-centered stellar eclipse visibility');
console.log('renderLighting.test: ok');
