import * as THREE from 'three/webgpu';
import { SIMULATION } from '../core/constants.js';
import { densityKgM3, gravityVectorSamples, hillRadiusMeters, lagrangePointEstimates, orbitalPlaneBasis, overlayTargetPair, rocheLimitMeters } from '../cosmic/scientificOverlays.js';

function dispose(root){root.traverse?.((n)=>{n.geometry?.dispose?.();n.material?.dispose?.();});}
function lineLoopCircle(radius,color,opacity=.45,segments=128){const pts=[];for(let i=0;i<=segments;i+=1){const a=i/segments*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*radius,0,Math.sin(a)*radius));}const g=new THREE.BufferGeometry().setFromPoints(pts);return new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity,depthWrite:false,blending:THREE.AdditiveBlending}));}
function toRender(referenceFrame,p,out=new THREE.Vector3()){return referenceFrame.toRender(p,out);}

export function updateScientificOverlayVisual(scene,holder,{settings,target,bodies,ship,referenceFrame}){
  if(holder.group){scene.remove(holder.group);dispose(holder.group);}const group=new THREE.Group();group.name='scientific-overlays';holder.group=group;scene.add(group);
  if(!settings?.enabled)return {summary:'Overlays off'};
  const pair=overlayTargetPair(target,bodies);const summary=[];
  if(pair && settings.hill){const a=pair.secondary.semiMajorAxis||Math.hypot(pair.secondary.position[0]-pair.primary.position[0],pair.secondary.position[1]-pair.primary.position[1],pair.secondary.position[2]-pair.primary.position[2]);const r=hillRadiusMeters(pair.primary.mass,pair.secondary.mass,a,pair.secondary.eccentricity||0);if(Number.isFinite(r)){const c=toRender(referenceFrame,pair.secondary.position);const circle=lineLoopCircle(r/SIMULATION.metersPerRenderUnit,0x62eaff,.45);circle.position.copy(c);group.add(circle);summary.push(`Hill ${(r/1e6).toFixed(2)} Mm`);}}
  if(target && settings.roche){const rho=densityKgM3(target);const r=rocheLimitMeters(target.radius,rho,3000,true);if(Number.isFinite(r)){const c=toRender(referenceFrame,target.position);const circle=lineLoopCircle(r/SIMULATION.metersPerRenderUnit,0xff7ac8,.38);circle.position.copy(c);circle.rotation.x=Math.PI/2;group.add(circle);summary.push(`Roche ${(r/1e6).toFixed(2)} Mm`);}}
  if(pair && settings.lagrange){const pts=lagrangePointEstimates(pair.primary,pair.secondary);const arr=new Float32Array(pts.length*3);for(let i=0;i<pts.length;i+=1){const p=toRender(referenceFrame,pts[i].position);arr[i*3]=p.x;arr[i*3+1]=p.y;arr[i*3+2]=p.z;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(arr,3));group.add(new THREE.Points(g,new THREE.PointsMaterial({color:0xffdd7a,size:1.4,transparent:true,opacity:.9,depthWrite:false,blending:THREE.AdditiveBlending})));summary.push('L1–L5');}
  if(pair && settings.orbitPlane){const basis=orbitalPlaneBasis(pair.primary,pair.secondary);if(basis){const pts=[];for(let i=0;i<=160;i+=1){const a=i/160*Math.PI*2;const p=[basis.center[0]+(basis.x[0]*Math.cos(a)+basis.y[0]*Math.sin(a))*basis.radiusMeters,basis.center[1]+(basis.x[1]*Math.cos(a)+basis.y[1]*Math.sin(a))*basis.radiusMeters,basis.center[2]+(basis.x[2]*Math.cos(a)+basis.y[2]*Math.sin(a))*basis.radiusMeters];pts.push(toRender(referenceFrame,p).clone());}const g=new THREE.BufferGeometry().setFromPoints(pts);group.add(new THREE.Line(g,new THREE.LineBasicMaterial({color:0x75a8ff,transparent:true,opacity:.3,depthWrite:false})));summary.push('orbit plane');}}
  if(ship && settings.gravity){const span=Math.max(2e8,Math.min(2e10,target?Math.hypot(target.position[0]-ship.position[0],target.position[1]-ship.position[1],target.position[2]-ship.position[2])*.35:2e9));const samples=gravityVectorSamples(ship.position,bodies,span,5);const seg=new Float32Array(samples.length*6);let max=1e-12;for(const s of samples)max=Math.max(max,s.magnitudeMps2);for(let i=0;i<samples.length;i+=1){const s=samples[i],p0=toRender(referenceFrame,s.position),m=s.magnitudeMps2,scaleMeters=span*.12*Math.min(1,Math.sqrt(m/max));const am=Math.hypot(...s.acceleration)||1;const end=[s.position[0]+s.acceleration[0]/am*scaleMeters,s.position[1]+s.acceleration[1]/am*scaleMeters,s.position[2]+s.acceleration[2]/am*scaleMeters],p1=toRender(referenceFrame,end);const k=i*6;seg[k]=p0.x;seg[k+1]=p0.y;seg[k+2]=p0.z;seg[k+3]=p1.x;seg[k+4]=p1.y;seg[k+5]=p1.z;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(seg,3));group.add(new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:0x85ffb0,transparent:true,opacity:.55,depthWrite:false,blending:THREE.AdditiveBlending})));summary.push('gravity vectors');}
  return {summary:summary.join(' · ')||'No applicable target overlays'};
}
